### ISSUE TITLE
20 Appendix C: Markup Selector Syntax

### ISSUE THREAD

**Issue by bufferings** [thymeleaf-docs-ja/thymeleaf-docs#4]
19じゃなくて20の間違いだろうけど。一旦、本家のままで。

**Comment by bufferings** [comment]
Issueあげといた。

https://github.com/thymeleaf/thymeleaf-docs/issues/48

**Comment by bufferings** [comment]
Issue対応されたのでタイトル20に変更しておいた。

**Comment by bufferings** [comment]
うしろから始めてみるか。

**Comment by MasatoshiTada** [comment]
レビューとマージ完了したので、クローズします。
